### ISSUE TITLE
Command didnt work

### ISSUE THREAD

**Issue by Maldohr** [z3nn13/custom-commands-yagpdb#2]
The Command do nothing if u type -roleinfo Role or -ri Role. Think the Trigger has some issues.

**Comment by paulphyo** [comment]
Apologies for the extensive time of response, but I'm not very active here. In case you still wish to add it, i'll type a reply either way.  The code's working fine as of now without any additional modifications. If the bot's not responding, i recommend trying these things:
1. Make sure you set the command trigger with the same one in the comment at the top of the roleinfo file.
2. Ensure you have at most 3 commands that are being executed in the channel (CC limit)
3. Ensure there are proper bot permissions in the channel
If issues still persist, you could either message me on discord or visit Yag's community server and inquire there. 
Thanks for opening an issue !
